-- Migration: 20260412000001_briefings_table.sql
-- Phase 3: briefings table for weekly AI briefing (S3)
-- Prerequisites: 20260409000000, 20260409000001 must be applied first

-- ============================================================
-- 1. briefings table
-- ============================================================

CREATE TABLE briefings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  wedding_id uuid NOT NULL REFERENCES weddings(id),
  planner_id uuid REFERENCES auth.users(id),
  -- NULL planner_id means system-generated (cron job)

  generated_at timestamptz NOT NULL DEFAULT now(),

  -- Four structured sections from AI generation
  overdue_section jsonb,
  -- Array of: { type: 'payment'|'task'|'vendor', label: text, detail: text, days_outstanding: integer, flagged_last_week: boolean }

  at_risk_section jsonb,
  -- Array of: { type: 'vendor'|'budget', label: text, detail: text, days_stalled: integer | null }

  upcoming_section jsonb,
  -- Array of: { type: 'decision'|'task', label: text, detail: text, due_date: text | null }

  budget_section jsonb,
  -- { planned_paise: integer, committed_paise: integer, paid_paise: integer, summary: text }

  is_all_clear boolean NOT NULL DEFAULT false,
  -- true when overdue_section and at_risk_section are both empty

  whatsapp_sent_at timestamptz,
  -- NULL until WhatsApp delivery confirmed (Phase 3 provider integration)

  prompt_version text NOT NULL DEFAULT 'v1.0-gemini',

  created_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

COMMENT ON TABLE briefings IS
  'Weekly AI-generated briefing records for planners and head planners. '
  'Generated by the generate-weekly-briefing Edge Function. '
  'One record per generation per wedding. Accessed in-app in reverse chronological order.';

-- ============================================================
-- 2. RLS — scoped to wedding participants
-- ============================================================

ALTER TABLE briefings ENABLE ROW LEVEL SECURITY;

-- Participants of the wedding can read briefings
CREATE POLICY "briefings_select" ON briefings FOR SELECT
  USING (
    deleted_at IS NULL
    AND EXISTS (
      SELECT 1 FROM participants p
      WHERE p.wedding_id = briefings.wedding_id
        AND p.user_id = auth.uid()
        AND p.status = 'active'
    )
  );

-- Only service role inserts (Edge Function uses service role key)
CREATE POLICY "briefings_insert" ON briefings FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

-- Soft delete only
CREATE POLICY "briefings_update" ON briefings FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM participants p
      WHERE p.wedding_id = briefings.wedding_id
        AND p.user_id = auth.uid()
        AND p.status = 'active'
        AND p.access_level IN ('planner_full', 'head_planner', 'full')
    )
  );

-- Hard deletes blocked
CREATE POLICY "briefings_delete" ON briefings FOR DELETE
  USING (false);

-- ============================================================
-- 3. Soft delete guard trigger
-- ============================================================

CREATE TRIGGER prevent_briefing_delete
  BEFORE DELETE ON briefings
  FOR EACH ROW EXECUTE FUNCTION guard_hard_delete();

-- ============================================================
-- 4. Indexes
-- ============================================================

CREATE INDEX idx_briefings_wedding_generated
  ON briefings(wedding_id, generated_at DESC)
  WHERE deleted_at IS NULL;

CREATE INDEX idx_briefings_wedding_id
  ON briefings(wedding_id)
  WHERE deleted_at IS NULL;
