-- Seed: event_category_defaults
-- Run in Supabase SQL Editor

TRUNCATE TABLE event_category_defaults;

INSERT INTO event_category_defaults (event_type, category_name, display_order) VALUES

  -- Haldi
  ('haldi', 'Photography', 1),
  ('haldi', 'Videography', 2),
  ('haldi', 'Mehendi', 3),
  ('haldi', 'Catering', 4),
  ('haldi', 'Decor', 5),
  ('haldi', 'Florist', 6),
  ('haldi', 'Makeup', 7),
  ('haldi', 'Hair Stylist', 8),
  ('haldi', 'Rangoli Artist', 9),

  -- Mehendi
  ('mehendi', 'Mehendi', 1),
  ('mehendi', 'Photography', 2),
  ('mehendi', 'Videography', 3),
  ('mehendi', 'Catering', 4),
  ('mehendi', 'Decor', 5),
  ('mehendi', 'Florist', 6),
  ('mehendi', 'Makeup', 7),
  ('mehendi', 'Hair Stylist', 8),
  ('mehendi', 'Live Music / Performer', 9),
  ('mehendi', 'Rangoli Artist', 10),

  -- Sangeet
  ('sangeet', 'Venue', 1),
  ('sangeet', 'Photography', 2),
  ('sangeet', 'Videography', 3),
  ('sangeet', 'DJ', 4),
  ('sangeet', 'Live Music / Performer', 5),
  ('sangeet', 'Choreographer', 6),
  ('sangeet', 'Catering', 7),
  ('sangeet', 'Decor', 8),
  ('sangeet', 'Lighting', 9),
  ('sangeet', 'Sound & AV', 10),
  ('sangeet', 'Makeup', 11),
  ('sangeet', 'Hair Stylist', 12),

  -- Engagement
  ('engagement', 'Venue', 1),
  ('engagement', 'Photography', 2),
  ('engagement', 'Videography', 3),
  ('engagement', 'Catering', 4),
  ('engagement', 'Decor', 5),
  ('engagement', 'Florist', 6),
  ('engagement', 'Makeup', 7),
  ('engagement', 'Hair Stylist', 8),
  ('engagement', 'Jewellery', 9),
  ('engagement', 'Bridal Wear', 10),
  ('engagement', 'Groom Wear', 11),
  ('engagement', 'Invitation Cards', 12),

  -- Wedding
  ('wedding', 'Venue', 1),
  ('wedding', 'Photography', 2),
  ('wedding', 'Videography', 3),
  ('wedding', 'Drone', 4),
  ('wedding', 'Catering', 5),
  ('wedding', 'Decor', 6),
  ('wedding', 'Florist', 7),
  ('wedding', 'Lighting', 8),
  ('wedding', 'Pandit / Priest', 9),
  ('wedding', 'Mehendi', 10),
  ('wedding', 'Band / Baraat', 11),
  ('wedding', 'Horse / Ghodi', 12),
  ('wedding', 'DJ', 13),
  ('wedding', 'Sound & AV', 14),
  ('wedding', 'Makeup', 15),
  ('wedding', 'Hair Stylist', 16),
  ('wedding', 'Bridal Wear', 17),
  ('wedding', 'Groom Wear', 18),
  ('wedding', 'Jewellery', 19),
  ('wedding', 'Invitation Cards', 20),
  ('wedding', 'Fireworks', 21),
  ('wedding', 'Transport', 22),
  ('wedding', 'Accommodation', 23),
  ('wedding', 'Event Coordinator', 24),
  ('wedding', 'Gifts & Favours', 25),
  ('wedding', 'Tent / Shamiana', 26),

  -- Reception
  ('reception', 'Venue', 1),
  ('reception', 'Photography', 2),
  ('reception', 'Videography', 3),
  ('reception', 'Drone', 4),
  ('reception', 'Catering', 5),
  ('reception', 'Decor', 6),
  ('reception', 'Florist', 7),
  ('reception', 'Lighting', 8),
  ('reception', 'DJ', 9),
  ('reception', 'Live Music / Performer', 10),
  ('reception', 'Sound & AV', 11),
  ('reception', 'Makeup', 12),
  ('reception', 'Hair Stylist', 13),
  ('reception', 'Bridal Wear', 14),
  ('reception', 'Groom Wear', 15),
  ('reception', 'Jewellery', 16),
  ('reception', 'Wedding Cake', 17),
  ('reception', 'Photo Booth', 18),
  ('reception', 'Fireworks', 19),
  ('reception', 'Transport', 20),
  ('reception', 'Accommodation', 21),
  ('reception', 'Gifts & Favours', 22);
